### ISSUE TITLE
error in bootstraping project via flactory

### ISSUE THREAD

**Issue by ShalbafZadeh** [mehdy/flactory#2]
when i try to create a new project by `flactory new` i get prompted to this options:

```
which template do you want to use [mehdy/default]: 
```

entering mehdy , default , reza or anyother name gives following error:

```
Traceback (most recent call last):
  File "/home/reza/envS/pycon/bin/flactory", line 9, in <module>
    load_entry_point('flactory==0.1.1', 'console_scripts', 'flactory')()
  File "/home/reza/envS/pycon/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/reza/envS/pycon/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/reza/envS/pycon/local/lib/python2.7/site-packages/click/core.py", line 1058, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
  File "/home/reza/envS/pycon/local/lib/python2.7/site-packages/click/core.py", line 620, in make_context
    self.parse_args(ctx, args)
  File "/home/reza/envS/pycon/local/lib/python2.7/site-packages/click/core.py", line 874, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/home/reza/envS/pycon/local/lib/python2.7/site-packages/click/core.py", line 1398, in handle_parse_result
    self.callback, ctx, self, value)
  File "/home/reza/envS/pycon/local/lib/python2.7/site-packages/click/core.py", line 77, in invoke_param_callback
    return callback(ctx, param, value)
  File "/home/reza/envS/pycon/local/lib/python2.7/site-packages/flactory.py", line 87, in check_template
    user, template = value.split('/')
ValueError: need more than 1 value to unpack
```

and just pressing enter give following error

```
Traceback (most recent call last):
  File "/home/reza/envS/pycon/bin/flactory", line 9, in <module>
    load_entry_point('flactory==0.1.1', 'console_scripts', 'flactory')()
  File "/home/reza/envS/pycon/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/reza/envS/pycon/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/reza/envS/pycon/local/lib/python2.7/site-packages/click/core.py", line 1058, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
  File "/home/reza/envS/pycon/local/lib/python2.7/site-packages/click/core.py", line 620, in make_context
    self.parse_args(ctx, args)
  File "/home/reza/envS/pycon/local/lib/python2.7/site-packages/click/core.py", line 874, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/home/reza/envS/pycon/local/lib/python2.7/site-packages/click/core.py", line 1398, in handle_parse_result
    self.callback, ctx, self, value)
  File "/home/reza/envS/pycon/local/lib/python2.7/site-packages/click/core.py", line 77, in invoke_param_callback
    return callback(ctx, param, value)
  File "/home/reza/envS/pycon/local/lib/python2.7/site-packages/flactory.py", line 88, in check_template
    if user in res.resource_listdir('flactory', 'templates'):
  File "/home/reza/envS/pycon/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1167, in resource_listdir
    resource_name
  File "/home/reza/envS/pycon/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1618, in resource_listdir
    return self._listdir(self._fn(self.module_path, resource_name))
  File "/home/reza/envS/pycon/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1706, in _listdir
    return os.listdir(path)
OSError: [Errno 2] No such file or directory: '/home/reza/envS/pycon/local/lib/python2.7/site-packages/templates'
```

if you manually create templates directory you will get this error:

```
user "mehdy" does not exist
```

and if you pass any name, you still will get this error:

```
ValueError: need more than 1 value to unpack
```

**Comment by mehdy** [comment]
fixed in version 0.2.0
